include:
  - board: seeeduino_xiao_ble
    shield: totem_left rgbled_widget
  - board: seeeduino_xiao_ble
    shield: totem_right rgbled_widget
  - board: seeeduino_xiao_ble
    shield: totem_dongle rgbled_widget
#  - board: seeeduino_xiao_ble
#    shield: settings_reset
